version: "3"

services:
  nest:
    env_file:
    - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${NODE_ENV}
      args:
      - NODE_ENV:${NODE_ENV}
    container_name: docker-nestjs-base-${NODE_ENV}
    image: ${IMAGE_NAME}-${NODE_ENV}:${IMAGE_TAG}


    volumes:
      - .:/app
    ports:
    - 3000:${SERVER_PORT}
    networks:
      - nesjs-network

networks:
  nesjs-network:
